import { NextResponse } from "next/server";
import { auth } from "@clerk/nextjs/server";
import { prisma } from "@/lib/db";
import { consumeCredits } from "@/lib/usage";
import { inngest } from "@/inngest/client";

/**
 * Initialize GitHub repo for a project
 * Creates a new GitHub repository with the specified name
 */
export async function POST(req: Request) {
  const session = await auth();
  const userId = (session as { userId?: string }).userId;
  if (!userId) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  let body: { projectId?: string; repoName?: string } = {};
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }

  const { projectId, repoName } = body;
  
  if (!projectId || !repoName) {
    return NextResponse.json({ 
      error: "projectId and repoName required" 
    }, { status: 400 });
  }

  // Get user's stored GitHub access token
  const user = await prisma.user.findUnique({
    where: { id: userId },
    select: { githubAccessToken: true, githubUsername: true },
  });

  if (!user?.githubAccessToken) {
    return NextResponse.json({ 
      error: "GitHub not connected",
      detail: "Please connect your GitHub account first" 
    }, { status: 403 });
  }

  const githubToken = user.githubAccessToken;

  // Validate repository name - GitHub doesn't allow certain characters
  const invalidChars = /[@\s!#$%^&*()+={}\[\]|\\:;"'<>,.?/]/;
  if (invalidChars.test(repoName)) {
    return NextResponse.json({ 
      error: "Invalid repository name",
      detail: "Repository name can only contain letters, numbers, hyphens (-), underscores (_), and periods (.). Cannot contain spaces, @, or other special characters."
    }, { status: 400 });
  }

  // Check for common invalid patterns
  if (repoName.startsWith('.') || repoName.startsWith('-')) {
    return NextResponse.json({ 
      error: "Invalid repository name",
      detail: "Repository name cannot start with a period (.) or hyphen (-)."
    }, { status: 400 });
  }

  if (repoName.endsWith('.')) {
    return NextResponse.json({ 
      error: "Invalid repository name",
      detail: "Repository name cannot end with a period (.)."
    }, { status: 400 });
  }

  console.log(`[GitHub Init] Creating repository: ${repoName} for project: ${projectId}`);

  // Verify project ownership
  const project = await prisma.project.findUnique({
    where: { id: projectId, userId },
  });

  if (!project) {
    return NextResponse.json({ 
      error: "Project not found or forbidden" 
    }, { status: 403 });
  }

  try {
    // Create GitHub repo using GitHub API
    const response = await fetch("https://api.github.com/user/repos", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${githubToken}`,
        "Content-Type": "application/json",
        Accept: "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
      },
      body: JSON.stringify({
        name: repoName,
        description: `Generated by Vibe - ${project.name}`,
        private: false,
        auto_init: true, // Initialize with README
      }),
    });

    if (!response.ok) {
      const error = await response.json();
      console.error(`[GitHub Init] Failed to create repository:`, {
        repoName,
        status: response.status,
        error
      });
      
      // Check if repository already exists
      if (response.status === 422 && error.errors?.some((e: { message?: string }) => 
        e.message?.toLowerCase().includes("already exists") || 
        e.message?.toLowerCase().includes("name already exists")
      )) {
        return NextResponse.json({ 
          error: "Repository already exists",
          detail: `A repository named '${repoName}' already exists in your GitHub account. Please use a different name or delete the existing repository first.`
        }, { status: 422 });
      }
      
      return NextResponse.json({ 
        error: "Failed to create GitHub repo",
        detail: error.message || "Unknown error"
      }, { status: response.status });
    }

    const repoData = await response.json();
    console.log(`[GitHub Init] Repository created successfully:`, {
      repoName,
      htmlUrl: repoData.html_url,
      owner: repoData.owner?.login
    });

    // Update project with GitHub info
    await prisma.project.update({
      where: { id: projectId },
      data: {
        githubRepoName: repoName,
        githubRepoUrl: repoData.html_url,
        githubEnabled: true,
      },
    });

    // Fetch the first user message (prompt) for this project
    const firstMessage = await prisma.message.findFirst({
      where: { projectId, role: "USER" },
      orderBy: { createdAt: "asc" },
      select: { content: true },
    });

    if (!firstMessage) {
      return NextResponse.json({
        error: "No prompt found for project",
        detail: "Cannot start workflow without an initial user prompt",
      }, { status: 500 });
    }

    // Consume credits only after GitHub is connected to avoid waste
    try {
      await consumeCredits();
    } catch {
      return NextResponse.json({
        error: "Insufficient credits",
        detail: "Please upgrade or wait for credits to reset before starting the build.",
      }, { status: 429 });
    }

    // Kick off the background code-agent workflow now that GitHub is ready
    await inngest.send({
      name: "code-agent/run",
      data: {
        value: firstMessage.content,
        projectId,
      },
    });

    return NextResponse.json({
      success: true,
      repoUrl: repoData.html_url,
      repoName: repoName,
      workflowStarted: true,
    });
  } catch (e) {
    const message = e instanceof Error ? e.message : "Unknown error";
    return NextResponse.json({ 
      error: "Failed to initialize GitHub repo", 
      detail: message 
    }, { status: 500 });
  }
}
